MVC_TicariOtomasyon/Models/Entities/Message.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC_TicariOtomasyon.Models.Entities
{
    public class Message
    {
        public int MessageId { get; set; }
        public string Sender { get; set; }
        public string Receiver { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
        public DateTime SendDate { get; set; }
        public bool IsRead { get; set; }

    }
}

MVC_TicariOtomasyon/Areas/CustomerPanel/Controllers/DefaultController.cs
using MVC_TicariOtomasyon.Context;
using MVC_TicariOtomasyon.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace MVC_TicariOtomasyon.Areas.CustomerPanel.Controllers
{
    public class DefaultController : Controller
    {
        TicariOtomasyonContext context = new TicariOtomasyonContext();
        [Authorize]
        public ActionResult Index()
        {
            ViewBag.baslik = "Müşteri Bİlgileri";

            var mail = (string)Session["CustomerMail"];
            var values = context.Customers.FirstOrDefault(x => x.Mail == mail);
            ViewBag.mail = mail;

            var customerİd = context.Customers.Where(x => x.Mail == mail).Select(x => x.CustomerId).FirstOrDefault();
            var toplamSatıs=context.SalesMovements.Where(x=>x.CustomerId==customerİd).Count();
            ViewBag.toplamsatis = toplamSatıs;

            var toplamTutar = context.SalesMovements.Where(x => x.CustomerId == customerİd).Sum(x => x.Amount).ToString() ;
            ViewBag.toplamTutar=toplamTutar;

            var toplamUrunSayisi = context.SalesMovements.Where(x => x.CustomerId == customerİd).Sum(y => y.Piece).ToString(); ;
            ViewBag.toplamUrunSayisi=toplamUrunSayisi;


            return View(values);
        }
        public PartialViewResult Messages()
        {
            var mail = (string)Session["CustomerMail"];
            var values = context.Messages.Where(x => x.Receiver == mail).ToList();
            return PartialView(values);
        }
        [HttpGet]
        public PartialViewResult Settings()
        {
            var mail = (string)Session["CustomerMail"];
            var values = context.Customers.FirstOrDefault(x => x.Mail == mail);
            ViewBag.mail = mail;
            return PartialView(values);
        }
        [HttpPost]
        public PartialViewResult Settings(Customer customer)
        {
            var mail = (string)Session["CustomerMail"];
            var values = context.Customers.FirstOrDefault(x => x.Mail == mail);
            values.Name = customer.Name;
            values.Surname = customer.Surname;
            values.Mail = customer.Mail;
            values.City = customer.City;
            values.Password = customer.Password;
            context.SaveChanges();
            return PartialView(values);
        }
        public ActionResult Orders()
        {
            ViewBag.baslik = "Sipariş Geçmişim";

            var mail = (string)Session["CustomerMail"];
            var id = context.Customers.Where(x => x.Mail == mail.ToString()).Select(y => y.CustomerId).FirstOrDefault();
            var values = context.SalesMovements.Where(x => x.CustomerId == id).ToList();
            return View(values);
        }
        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("Index", "Panel", new { area = "" });
        }

        public PartialViewResult Duyuru()
        {
            var values=context.Messages.Where(x=>x.Sender=="admin").ToList();
            return PartialView(values);
        }
    }
}

MVC_TicariOtomasyon/Areas/CustomerPanel/Controllers/MessageController.cs
using MVC_TicariOtomasyon.Context;
using MVC_TicariOtomasyon.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_TicariOtomasyon.Areas.CustomerPanel.Controllers
{
    public class MessageController : Controller
    {
        TicariOtomasyonContext _context = new TicariOtomasyonContext();
        public ActionResult MessageList()
        {

            ViewBag.baslik = "Mesajlar";
            var mail = (string)Session["CustomerMail"];
            var values = _context.Messages.Where(x => x.Receiver == mail).ToList();
            return View(values);
        }
        public ActionResult SendMessageBox()
        {
            ViewBag.baslik = "Gönderilen Mesajlar";
            var mail = (string)Session["CustomerMail"];
            var values = _context.Messages.Where(x => x.Sender == mail).ToList();
            return View(values);
        }
        public ActionResult MessageDetail(int id)
        {
            ViewBag.baslik = "Mesaj Detayları";
            var mail = (string)Session["CustomerMail"];
            var values = _context.Messages.Where(x => x.MessageId == id).FirstOrDefault();
            return View(values);
        }
        [HttpGet]
        public ActionResult NewMessage()
        {
            ViewBag.baslik = "Yeni Mesaj Oluştur";
            return View();
        }
        [HttpPost]
        public ActionResult NewMessage(Message message)
        {
            var mail = (string)Session["CustomerMail"];
            message.SendDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            message.Sender = mail;
            _context.Messages.Add(message);
            _context.SaveChanges();
            return RedirectToAction("SendMessageBox", "Message", new { area = "CustomerPanel" });
        }
        public PartialViewResult MessageColmd3()
        {
            var mail = (string)Session["CustomerMail"];
            var inboxCount = _context.Messages.Count(x => x.Receiver == mail);
            var sendboxCount = _context.Messages.Count(x => x.Sender == mail);
            ViewBag.inboxCount = inboxCount;
            ViewBag.sendboxCount = sendboxCount;
            return PartialView();
        }
    }
}

MVC_TicariOtomasyon/Areas/CustomerPanel/Views/Default/Duyuru.cshtml
@model List<MVC_TicariOtomasyon.Models.Entities.Message>

<div class="tab-pane" id="timeline">

    <div class="timeline timeline-inverse">

        @foreach (var item in Model)
        {

            <div class="time-label">

                <span class="bg-warning">

                    @item.SendDate.ToShortDateString()

                </span>

            </div>

            <div>

                <i class="fas fa-envelope bg-primary"></i>

                <div class="timeline-item">

                    <span class="time"><i class="far fa-clock"></i> 12:05</span>

                    <h3 class="timeline-header"><a href="#">@item.Subject</a></h3>

                    <div class="timeline-body">
                        @item.Content

                    </div>


                </div>

            </div>

        }

    </div>

</div>

MVC_TicariOtomasyon/Areas/CustomerPanel/Views/Default/Index.cshtml
@model MVC_TicariOtomasyon.Models.Entities.Customer
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/CustomerPanel/Views/CustomerLayout/Index.cshtml";
}

<!DOCTYPE html>

<html>




<body class="hold-transition sidebar-mini">

    <div class="wrapper">
        <section class="content">

            <div class="container-fluid">

                <div class="row">

                    <div class="col-md-3">


                        <div class="card card-primary card-outline">

                            <div class="card-body box-profile">

                                <div class="text-center">

                                    <img class="profile-user-img img-fluid img-circle"
                                         src="~/AdminLTE-3.0.4/dist/img/user4-128x128.jpg"
                                         alt="User profile picture">

                                </div>

                                <h3 class="profile-username text-center">@Model.Name @Model.Surname</h3>

                                <p class="text-muted text-center">@Model.Mail</p>

                                <ul class="list-group list-group-unbordered mb-3">

                                    <li class="list-group-item">

                                        <b>Toplam Satış :</b> <a class="float-right">@ViewBag.toplamsatis</a>

                                    </li>

                                    <li class="list-group-item">

                                        <b>Toplam Satış Tutarı :</b> <a class="float-right">@ViewBag.toplamTutar</a>

                                    </li>

                                    <li class="list-group-item">

                                        <b>Toplam Ürün Sayısı :</b> <a class="float-right">@ViewBag.toplamUrunSayisi</a>

                                    </li>

                                </ul>

                                <a href="/CustomerPanel/Cargo/Index" class="btn btn-primary btn-block"><b>Kargo Takip</b></a>

                            </div>

                        </div>

                        <div class="card card-primary">

                            <div class="card-header">

                                <h3 class="card-title">Hakkında</h3>

                            </div>

                            <div class="card-body">

                                <strong><i class="fas fa-book mr-1"></i> Meslek</strong>

                                <p class="text-muted">

                                    Yazılım mühendisi

                                </p>

                                <hr>

                                <strong><i class="fas fa-map-marker-alt mr-1"></i> Şehir</strong>

                                <p class="text-muted">@Model.City</p>

                                <hr>

                                <strong><i class="fas fa-pencil-alt mr-1"></i> Telefon</strong>

                                <p class="text-muted">

                                    <span class="tag tag-danger">(000-000-000)</span>

                                </p>

                                <hr>

                                <strong><i class="far fa-file-alt mr-1"></i> Duyurular</strong>

                                <p class="text-muted">Yeni Ürünlerimiz İçin web sitemizi ziyaret edin.</p>

                            </div>

                        </div>

                    </div>

                    <div class="col-md-9">

                        <div class="card">

                            <div class="card-header p-2">

                                <ul class="nav nav-pills">

                                    <li class="nav-item"><a class="nav-link active" href="#messages" data-toggle="tab">Mesajlar</a></li>

                                    <li class="nav-item"><a class="nav-link" href="#timeline" data-toggle="tab">Duyurular</a></li>

                                    <li class="nav-item"><a class="nav-link" href="#settings" data-toggle="tab">Ayarlar</a></li>

                                </ul>

                            </div>

                            <div class="card-body">

                                <div class="tab-content">

                                    @Html.Action("Messages", "Default", new { Area = "CustomerPanel" })

                                    <!-- /.tab-pane -->

                                    @Html.Action("Duyuru", "Default", new { Area = "CustomerPanel" })

                                    <!-- /.tab-pane -->

                                    @Html.Action("Settings", "Default", new { Area = "CustomerPanel" })

                                    <!-- /.tab-pane -->

                                </div>

                                <!-- /.tab-content -->

                            </div><!-- /.card-body -->

                        </div>

                        <!-- /.nav-tabs-custom -->

                    </div>

                    <!-- /.col -->

                </div>

                <!-- /.row -->

            </div><!-- /.container-fluid -->

        </section>

        <!-- /.content -->

    </div>

</body>

</html>

MVC_TicariOtomasyon/Areas/CustomerPanel/Views/Default/Messages.cshtml
@model List<MVC_TicariOtomasyon.Models.Entities.Message>
<div class="active tab-pane" id="messages">
    @foreach (var item in Model)
    {

        <div class="post">

            <div class="user-block">

                <img class="img-circle img-bordered-sm" src="~/AdminLTE-3.0.4/dist/img/user1-128x128.jpg" alt="user image">

                <span class="username">

                    <a href="#">@item.Sender</a>

                    <a href="#" class="float-right btn-tool"><i class="fas fa-times"></i></a>

                </span>

                <span class="description">@item.Subject - @item.SendDate.ToShortDateString()</span>

            </div>

            <!-- /.user-block -->

            <p>

                @item.Content

            </p>

        </div>
    }

</div>

MVC_TicariOtomasyon/Areas/CustomerPanel/Views/Default/Orders.cshtml
@model List<MVC_TicariOtomasyon.Models.Entities.SalesMovement>
@{
    ViewBag.Title = "Orders";
    Layout = "~/Areas/CustomerPanel/Views/CustomerLayout/Index.cshtml";
}


<table class="table table-bordered">
    <tr>
        <th>Ürün Adı</th>
        <th>Fiyat</th>
        <th>Tarih</th>
    </tr>
    @foreach(var item in Model)
            {
                <tr>
                    <td>@item.Product.ProductName</td>
                    <td>@item.Price</td>
                    <td>@item.Date</td>
                </tr>
            }
</table>

MVC_TicariOtomasyon/Areas/CustomerPanel/Views/Default/Settings.cshtml
@model MVC_TicariOtomasyon.Models.Entities.Customer
<div class="tab-pane" id="settings">

    <form class="form-horizontal" method="post">

        <div class="form-group row">

            <label for="inputName" class="col-sm-2 col-form-label">Ad</label>

            <div class="col-sm-10">

                @Html.TextBoxFor(x => x.Name, new { @class = "form-control", type = "text" })              
            </div>

        </div>

        <div class="form-group row">

            <label for="inputName2" class="col-sm-2 col-form-label">Soyad</label>

            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Surname, new { @class = "form-control", type = "text" })
           

            </div>

        </div>
        <div class="form-group row">

            <label for="city" class="col-sm-2 col-form-label">Şehir</label>

            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.City, new { @class = "form-control", type = "text" })              
            </div>

        </div>


        <div class="form-group row">

            <label for="inputEmail" class="col-sm-2 col-form-label">Email</label>

            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Mail, new { @class = "form-control", type = "email", @readonly = "readonly" })               
            </div>

        </div>

        <div class="form-group row">

            <label for="password" class="col-sm-2 col-form-label">Şifre</label>

            <div class="col-sm-10">
                @Html.TextBoxFor(x => x.Password, new { @class = "form-control", type = "password", id = "password" })
            </div>

        </div>

        <div class="form-group row">

            <div class="offset-sm-2 col-sm-10">

                <div class="checkbox">

                    <label>

                        <input type="checkbox"> Şifremi değiştirmek istiyorum <a href="#"></a>

                    </label>

                </div>

            </div>

        </div>

        <div class="form-group row">

            <div class="offset-sm-2 col-sm-10">

                <button type="submit" class="btn btn-danger">Bilgilerimi Güncelle</button>

            </div>

        </div>

    </form>

</div>

@*<form method="post">
        <table class="table table-bordered">
            <tr>
                <td> <label> Mail Adresi:@HttpContext.Current.User.Identity.Name </label></td>
            </tr>
            <tr>

                <td>
                    <label>Ad</label>
                @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                </td>
            </tr>
            <tr>

                <td>
                    <label>Soyad</label>
                    @Html.TextBoxFor(x => x.Surname, new { @class = "form-control" })
                </td>
            </tr>
            <tr>
                <td>
                    <label>Şehir</label>
                    @Html.TextBoxFor(x => x.City, new { @class = "form-control" })
                </td>
            </tr>
            <tr>
                <td>
                    <label>Şifre</label>
                    @Html.TextBoxFor(x => x.Password, new { @class = "form-control" })
                </td>
            </tr>
        </table>
        <button class="btn btn-warning"> Bilgilerimi Güncelle</button>
    </form>*@