MVC_TicariOtomasyon/Models/Entities/ToDoList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC_TicariOtomasyon.Models.Entities
{
    public class ToDoList
    {
        public int ToDoListId { get; set; }
        public string Baslik { get; set; }
        public bool Status { get; set; }
    }
}

MVC_TicariOtomasyon/Areas/Admin/Controllers/ToDoListController.cs
using MVC_TicariOtomasyon.Context;
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace MVC_TicariOtomasyon.Areas.Admin.Controllers
{
    public class ToDoListController : Controller
    {
        TicariOtomasyonContext context=new TicariOtomasyonContext();
        public ActionResult Index()
        {
            var musteriSayisi=context.Customers.Count().ToString();
            ViewBag.mSayi=musteriSayisi;

            var urunSayisi=context.Products.Count().ToString();
            ViewBag.urunSayi=urunSayisi;

            var kategoriSayisi=context.Categories.Count().ToString();
            ViewBag.kSayisi=kategoriSayisi;

            var sehirSayisi=context.Customers.Select(x => x.City).Distinct().Count().ToString();
            ViewBag.sehirSayi=sehirSayisi;
      
            return View();
        }
        public PartialViewResult Todo()
        {
            var todo = context.ToDoLists.ToList();
            return PartialView(todo);
        }
    }
}

MVC_TicariOtomasyon/Areas/Admin/Views/ToDoList/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/AdminLayout/Index.cshtml";
}

<section class="content ">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-info">
                    <div class="inner">
                        <h3>@ViewBag.urunSayi</h3>

                        <p>Toplam Ürün Sayısı</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-bag"></i>
                    </div>
                    <a href="#" class="small-box-footer"> <i class=""></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-success">
                    <div class="inner">
                        <h3>@ViewBag.sehirSayi<sup style="font-size: 20px"></sup></h3>

                        <p>Şehir Sayısı</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                    </div>
                    <a href="#" class="small-box-footer"><i class=""></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-warning">
                    <div class="inner">
                        <h3>@ViewBag.mSayi</h3>

                        <p>Toplam Müşteri Sayısı</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-person-add"></i>
                    </div>
                    <a href="#" class="small-box-footer"> <i class=""></i></a>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-6">
                <!-- small box -->
                <div class="small-box bg-danger">
                    <div class="inner">
                        <h3>@ViewBag.kSayisi</h3>

                        <p>Kategori Sayısı</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-pie-graph"></i>
                    </div>
                    <a href="#" class="small-box-footer"><i class=""></i></a>
                </div>
            </div>
            <!-- ./col -->
        </div>
        <!-- /.row -->
        <!-- Main row -->
       @Html.Action("Todo","ToDoList","Admin")

    </div>
</section>

MVC_TicariOtomasyon/Areas/Admin/Views/ToDoList/Todo.cshtml
@model List<MVC_TicariOtomasyon.Models.Entities.ToDoList>
<div class="row">
    <!-- Left col -->




    <div class="card col-lg-12">
        <div class="card-header">
            <h3 class="card-title">
                <i class="ion ion-clipboard mr-1"></i>
               Yapılacaklar Listesi
            </h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <ul class="todo-list" data-widget="todo-list">
                @foreach (var item in Model)
                {

                    <li>
                        <!-- drag handle -->
                        <span class="handle">
                            <i class="fas fa-ellipsis-v"></i>
                            <i class="fas fa-ellipsis-v"></i>
                        </span>
                        <!-- checkbox -->
                        <div class="icheck-primary d-inline ml-2">
                            <input type="checkbox" value="" name="todo1" id="@item.ToDoListId">
                            <label for="@item.ToDoListId"></label>
                        </div>
                        <!-- todo text -->
                        <span class="text">@item.Baslik</span>
                        <!-- Emphasis label -->
                        <small class="badge badge-danger"><i class="far fa-clock"></i></small>
                        <!-- General tools such as edit or delete-->
                        <div class="tools">
                            <i class="fas fa-edit"></i>
                            <i class="fas fa-trash-o"></i>
                        </div>
                    </li>
                }
                <!-- /.card -->
            </ul>
        </div>
    </div>